class ActionKind(Enum):
    Walking = 0
    Idle = 1
    Jumping = 2
@namespace
class SpriteKind:
    goal = SpriteKind.create()
    coin = SpriteKind.create()
    falsa = SpriteKind.create()
    P = SpriteKind.create()
    meta = SpriteKind.create()

def on_on_overlap(sprite, otherSprite):
    game.set_game_over_message(False, "es shrek es raro...")
    game.game_over(False)
sprites.on_overlap(SpriteKind.player, SpriteKind.falsa, on_on_overlap)

def startarget():
    global meta2, goal2, goal_falsa, money
    scene.place_on_random_tile(mySprite, 1)
    meta2 = sprites.create(assets.image("""
        shrek0
    """), SpriteKind.meta)
    goal2 = sprites.create(assets.image("""
        shrek
    """), SpriteKind.goal)
    goal_falsa = sprites.create(assets.image("""
        shrek falso
    """), SpriteKind.falsa)
    scene.place_on_random_tile(goal2, 2)
    scene.place_on_random_tile(meta2, 14)
    scene.place_on_random_tile(goal_falsa, 3)
    for value in scene.get_tiles_by_type(5):
        money = sprites.create(assets.image("""
            Moneda
        """), SpriteKind.coin)
        scene.place(value, money)
        animation.attach_animation(money, animcoin)
        animation.set_action(money, ActionKind.Walking)

def on_right_pressed():
    animation.run_image_animation(mySprite,
        assets.animation("""
            mono derecha
        """),
        200,
        True)
controller.right.on_event(ControllerButtonEvent.PRESSED, on_right_pressed)

def on_left_pressed():
    animation.run_image_animation(mySprite,
        assets.animation("""
            mono izquierda
        """),
        200,
        True)
controller.left.on_event(ControllerButtonEvent.PRESSED, on_left_pressed)

def on_on_overlap2(sprite2, otherSprite2):
    sprites.destroy(otherSprite2)
    info.change_score_by(1)
    music.play(music.melody_playable(music.ba_ding),
        music.PlaybackMode.UNTIL_DONE)
sprites.on_overlap(SpriteKind.player, SpriteKind.coin, on_on_overlap2)

def on_up_pressed():
    global jump
    if mySprite.is_hitting_tile(CollisionDirection.BOTTOM):
        mySprite.vy = -150
    elif jump == 0:
        mySprite.vy = -150
        jump = 1
controller.up.on_event(ControllerButtonEvent.PRESSED, on_up_pressed)

def on_overlap_tile(sprite3, location):
    game.set_game_over_message(False, "¡los monos no nadan!")
    game.game_over(False)
scene.on_overlap_tile(SpriteKind.player,
    assets.image("""
        agua
    """),
    on_overlap_tile)

def on_on_overlap3(sprite4, otherSprite3):
    global change_level
    if change_level == 0:
        sprites.destroy_all_sprites_of_kind(SpriteKind.goal)
        sprites.destroy_all_sprites_of_kind(SpriteKind.coin)
        sprites.destroy_all_sprites_of_kind(SpriteKind.falsa)
        sprites.destroy_all_sprites_of_kind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.set_tile_map(assets.image("""
            segundo nivel
        """))
        startanimcoin()
        startstage()
        startarget()
    elif change_level == 1:
        sprites.destroy_all_sprites_of_kind(SpriteKind.falsa)
        sprites.destroy_all_sprites_of_kind(SpriteKind.goal)
        sprites.destroy_all_sprites_of_kind(SpriteKind.coin)
        sprites.destroy_all_sprites_of_kind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.set_tile_map(assets.image("""
            tercer nivel
        """))
        startanimcoin()
        startstage()
        startarget()
    elif change_level == 2:
        sprites.destroy_all_sprites_of_kind(SpriteKind.goal)
        sprites.destroy_all_sprites_of_kind(SpriteKind.coin)
        sprites.destroy_all_sprites_of_kind(SpriteKind.falsa)
        sprites.destroy_all_sprites_of_kind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.set_tile_map(assets.image("""
            cuarto nivel
        """))
        startanimcoin()
        startstage()
        startarget()
    elif change_level == 3:
        sprites.destroy_all_sprites_of_kind(SpriteKind.falsa)
        sprites.destroy_all_sprites_of_kind(SpriteKind.goal)
        sprites.destroy_all_sprites_of_kind(SpriteKind.coin)
        sprites.destroy_all_sprites_of_kind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.set_tile_map(assets.image("""
            quinto nivel
        """))
        startanimcoin()
        startstage()
        startarget()
    elif change_level == 4:
        sprites.destroy_all_sprites_of_kind(SpriteKind.coin)
        sprites.destroy_all_sprites_of_kind(SpriteKind.falsa)
        sprites.destroy_all_sprites_of_kind(SpriteKind.goal)
        sprites.destroy_all_sprites_of_kind(SpriteKind.meta)
        game.splash("nivel completado")
        scene.set_tile_map(img("""
            ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        .......77777ff7777777777777777777...........................
                        .......75............777777777777...........................
                        .......7777777777..7.777777777777...........................
                        ............7......7.75.........7...........................
                        ............7...7777.7777777....7...........................
                        ............7......747.....77...4...........................
                        ............7.7.............77..7...........................
                        .1............7.................7...........2...............
                        .77777777777777777777777777777777777777777777777............
                        999999999999999999999999999999999999999999999999999999999999
        """))
        change_level += 1
        startanimcoin()
        startstage()
        startarget()
    elif change_level == 5:
        sprites.destroy_all_sprites_of_kind(SpriteKind.falsa)
        sprites.destroy_all_sprites_of_kind(SpriteKind.coin)
        sprites.destroy_all_sprites_of_kind(SpriteKind.goal)
        sprites.destroy_all_sprites_of_kind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.set_tile_map(img("""
            ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        .............77..7..8888888.................................
                        ..........57....8...........................................
                        .........57....8............................................
                        .....1...7....8.............................................
                        ....77777...58..............5...............................
                        ............8................2..............................
                        ............................................................
                        999999999999999999999999999999999999999999999999999999999999
        """))
        startanimcoin()
        startstage()
        startarget()
    elif change_level == 6:
        sprites.destroy_all_sprites_of_kind(SpriteKind.coin)
        sprites.destroy_all_sprites_of_kind(SpriteKind.goal)
        sprites.destroy_all_sprites_of_kind(SpriteKind.falsa)
        sprites.destroy_all_sprites_of_kind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.set_tile_map(img("""
            ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ...............7....77....7.................................
                        ..............77..77..77..77................................
                        ................77......77..................................
                        ...............7..........7.................................
                        ...............7...........7................................
                        ...............75.......1...7...............................
                        ...............7............7...............................
                        ...............7............7...............................
                        ................7...........7...............................
                        .................77........7................................
                        ..................77....7777................................
                        ...................4...77...................................
                        ...................4...4....................................
                        ...................4...4....................................
                        ...................4...4....................................
                        ...................4...4....................................
                        ...................4...4....................................
                        ...................4...4....................................
                        ...................4...4....................................
                        ...................4...4....................................
                        ...................4...4....................................
                        ...................4...4....................................
                        ............................................................
                        ............5..............5................................
                        ............5..............5................................
                        ...........555............555...............................
                        ..........7.5..............5..7.............................
                        ..........7....7777777777.....7.............................
                        ..........7....7........7.....7.............................
                        ..........7....7........7.....7.............................
                        ..........7....7........7.....7.............................
                        ..........7....7........7.....7.............................
                        ..........7....7........7.....7.............................
                        ..........7....7........7.....7.............................
                        ..........7....7........7.....7.............................
                        ..........7....7........7.....7.............................
                        ..........73...7........7.....7.............................
                        ..........777777........72....7.............................
                        ........................7777777.............................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        999999999999999999999999999999999999999999999999999999999999
        """))
        startanimcoin()
        startstage()
        startarget()
    elif change_level == 7:
        sprites.destroy_all_sprites_of_kind(SpriteKind.coin)
        sprites.destroy_all_sprites_of_kind(SpriteKind.goal)
        sprites.destroy_all_sprites_of_kind(SpriteKind.falsa)
        sprites.destroy_all_sprites_of_kind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.set_tile_map(img("""
            ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        .1..........................................................
                        ............................................................
                        7777fff888777....8887ff7....................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        .....2......................................................
                        .....888....................................................
                        .....888....................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        .99999999999999999999999999999999999999999999999999999999999
        """))
        startanimcoin()
        startarget()
        startstage()
    elif change_level == 8:
        sprites.destroy_all_sprites_of_kind(SpriteKind.coin)
        sprites.destroy_all_sprites_of_kind(SpriteKind.goal)
        sprites.destroy_all_sprites_of_kind(SpriteKind.falsa)
        sprites.destroy_all_sprites_of_kind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.set_tile_map(img("""
            ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ...........1...........ae...................................
                        ...........777777777777777..................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        ............................................................
                        999999999999999999999999999999999999999999999999999999999999
        """))
        startanimcoin()
        startarget()
        startstage()
sprites.on_overlap(SpriteKind.player, SpriteKind.goal, on_on_overlap3)

def startanimcoin():
    global animcoin
    animcoin = animation.create_animation(ActionKind.Walking, 200)
    animcoin.add_animation_frame(assets.image("""
        moneda 1
    """))
    animcoin.add_animation_frame(assets.image("""
        moneda 2
    """))
    animcoin.add_animation_frame(assets.image("""
        moneda 3
    """))
    animcoin.add_animation_frame(assets.image("""
        moneda 4
    """))
    animcoin.add_animation_frame(assets.image("""
        moneda 6
    """))
    animcoin.add_animation_frame(assets.image("""
        moneda 7
    """))
def startstage():
    scene.set_background_color(9)
    scene.set_tile(7, assets.image("""
        pasto
    """), True)
    scene.set_tile(1, assets.image("""
        inicio
    """), False)
    scene.set_tile(2, assets.image("""
        final
    """), False)
    scene.set_tile(5, assets.image("""
        comida
    """), False)
    scene.set_tile(9, assets.image("""
        Agua
    """), False)
    scene.set_tile(4, assets.image("""
        Bola
    """), False)
    scene.set_tile(15, assets.image("""
        pasto falso
    """), False)
    scene.set_tile(3, assets.image("""
        final falso
    """), False)
    scene.set_tile(8, assets.image("""
        final falso
    """), True)
    scene.set_tile(14, assets.image("""
        final falso
    """), False)
    scene.set_tile(10, assets.image("""
        final falso
    """), False)

def on_overlap_tile2(sprite5, location2):
    game.set_game_over_message(False, "¡ay!")
    game.game_over(False)
scene.on_overlap_tile(SpriteKind.player,
    assets.image("""
        bola
    """),
    on_overlap_tile2)

def on_on_overlap4(sprite6, otherSprite4):
    sprites.destroy_all_sprites_of_kind(SpriteKind.player)
    animation.run_image_animation(meta2,
        [img("""
                .................................7..777..7........
                        ................................77.77777.77.......
                        ..................................7777777.........
                        ..................................ee7ee77.........
                        .................................7f77f777.........
                        .................................777774777........
                        .................................744447777........
                        .................................777777777........
                        ........fffff.................bbe77777777eee......
                        .......feeeeef................beee77777eeeebbb....
                        ......feeeddddf..............bbeeeebbeeeeeebbb....
                        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
                        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
                        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
                        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
                        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
                        .fef..ffeedddddf............777bbbbbbbbbb7777b....
                        .fef.feeeefffff..............774444444444477......
                        .feffeeeeeeef..................bbbbbbbbbbbb.......
                        ..ffeeeefeffef.................bb44bbbbb44b.......
                        ...feeeefeffef...................44.....44........
                        ....feffbdfbdf....................4.....4.........
                        ....fdbbddcddf...................ee.....ee........
                        .....ffffffff..................eeee.....eeee......
            """),
            img("""
                .................................7..777..7........
                        ................................77.77777.77.......
                        ..................................7777777.........
                        ..................................ee7ee77.........
                        .................................7f77f777.........
                        .................................777774777........
                        .................................744447777........
                        .................................777777777........
                        ........fffff.................bbe77777777eee......
                        .......feeeeef................beee77777eeeebbb....
                        ......feeeddddf..............bbeeeebbeeeeeebbb....
                        .....ffeedfddddc............bbeeeee44eeeeeebbbbb..
                        ....fddeedfddffc...........bbbeeeeebbeeeeeeebbbb..
                        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
                        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
                        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
                        .fef..ffeedddddf............777bbbbbbbbbb7777b....
                        .fef.feeeefffff..............774444444444477......
                        .feffeeeeeeef..................bbbbbbbbbbbb.......
                        ..ffeeeefeffef.................bb44bbbbb44b.......
                        ...feeeefeffef...................44.....44........
                        ....feffbdfbdf....................4.....4.........
                        ....fdbbddcddf...................ee.....ee........
                        .....ffffffff..................eeee.....eeee......
            """),
            img("""
                .................................7..777..7........
                        ................................77.77777.77.......
                        ..................................7777777.........
                        ..................................ee7ee77.........
                        .................................7f77f777.........
                        .................................777774777........
                        .................................744447777........
                        .................................777777777........
                        ........fffff.................bbe77777777eee......
                        .......feeeeef................beee77777eeeebbb....
                        ......feeeddddf..............bbeeeebbeeeeeebbb....
                        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
                        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
                        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
                        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
                        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
                        .fef..ffeedddddf............777bbbbbbbbbb7777b....
                        .fef.feeeefffff..............774444444444477......
                        .feffeeeeeeef..................bbbbbbbbbbbb.......
                        ..ffeeeefeffef.................bb44bbbbb44b.......
                        ...feeeefeffef...................44.....44........
                        ....feffbdfbdf....................4.....4.........
                        ....fdbbddcddf...................ee.....ee........
                        .....ffffffff..................eeee.....eeee......
            """),
            img("""
                .................................7..777..7........
                        ................................77.77777.77.......
                        ..................................7777777.........
                        ..................................ee7ee77.........
                        .................................7f77f777.........
                        .................................777774777........
                        .................................744447777........
                        .................................777777777........
                        ........fffff.................bbe77777777eee......
                        .......feeeeef................beee77777eeeebbb....
                        ......feeeddddf..............bbeeeebbeeeeeebbb....
                        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
                        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
                        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
                        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
                        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
                        .fef..ffeedddddff...........777bbbbbbbbbb7777b....
                        .fef.feeeeffffffdf...........774444444444477......
                        .feffeeeeeeef.feddf............bbbbbbbbbbbb.......
                        ..ffeeeefeeeefeeef.............bb44bbbbb44b.......
                        ...feeeefeeeeeeef................44.....44........
                        ....feffbdffeeef..................4.....4.........
                        ....fdbbddf.fff..................ee.....ee........
                        .....fffff.....................eeee.....eeee......
            """),
            img("""
                .................................7..777..7........
                        ................................77.77777.77.......
                        ..................................7777777.........
                        ..................................ee7ee77.........
                        .................................7f77f777.........
                        .................................777774777........
                        .................................744447777........
                        .................................777777777........
                        ........fffff.................bbe77777777eee......
                        .......feeeeef................beee77777eeeebbb....
                        ......feeeddddf..............bbeeeebbeeeeeebbb....
                        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
                        ....fddeedfddfdc..2.2......bbbeeeeebbeeeeeeebbbb..
                        ....cdbeeddddeedc.222......bbbbbbbbbbbbbbb77bbbb..
                        .ff.cdbeeddcddddc..2........77bbbbbbbbbbbb77bbb...
                        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
                        .fef..ffeedddddff...........777bbbbbbbbbb7777b....
                        .fef.feeeefffff..f...........774444444444477......
                        .feffeeeeeeef...fdf............bbbbbbbbbbbb.......
                        ..ffeeeefeeeefffeddf...........bb44bbbbb44b.......
                        ...feeeefeeeeefeeef..............44.....44........
                        ....feffbdffeeeeef................4.....4.........
                        ....fdbbddf.fffff................ee.....ee........
                        .....fffff.....................eeee.....eeee......
            """),
            img("""
                .................................7..777..7........
                        ................................77.77777.77.......
                        ..................................7777777.........
                        ..................................ee7ee77.........
                        .................................7f77f777.........
                        .................................777774777........
                        .................................744447777........
                        .................................777777777........
                        ........fffff.................bbe77777777eee......
                        .......feeeeef.......2.2......beee77777eeeebbb....
                        ......feeeddddf......222.....bbeeeebbeeeeeebbb....
                        .....ffeedfddfdc......2.....bbeeeee44eeeeeebbbbb..
                        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
                        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
                        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
                        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
                        .fef..ffeedddddff...........777bbbbbbbbbb7777b....
                        .fef.feeeefffff..f...........774444444444477......
                        .feffeeeeeeef...fdf............bbbbbbbbbbbb.......
                        ..ffeeeefeeeefffeddf...........bb44bbbbb44b.......
                        ...feeeefeeeeefeeef..............44.....44........
                        ....feffbdffeeeeef................4.....4.........
                        ....fdbbddf.fffff................ee.....ee........
                        .....fffff.....................eeee.....eeee......
            """),
            img("""
                .................................7..777..7........
                        ................................77.77777.77.......
                        ..................................7777777.........
                        ..................................ee7ee77.........
                        .................................7f77f777.........
                        ............................2.2..777774777........
                        ............................222..744447777........
                        .............................2...777777777........
                        ........fffff.................bbe77777777eee......
                        .......feeeeef................beee77777eeeebbb....
                        ......feeeddddf..............bbeeeebbeeeeeebbb....
                        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
                        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
                        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
                        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
                        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
                        .fef..ffeedddddff...........777bbbbbbbbbb7777b....
                        .fef.feeeefffff..f...........774444444444477......
                        .feffeeeeeeef...fdf............bbbbbbbbbbbb.......
                        ..ffeeeefeeeefffeddf...........bb44bbbbb44b.......
                        ...feeeefeeeeefeeef..............44.....44........
                        ....feffbdffeeeeef................4.....4.........
                        ....fdbbddf.fffff................ee.....ee........
                        .....fffff.....................eeee.....eeee......
            """),
            img("""
                .................................7..777..7........
                ................................77.77777.77.......
                ..................................7777777.........
                ..................................ee7ee77.........
                .................................7f77f777.........
                .................................777774337........
                .................................744447777........
                .................................777777777........
                ........fffff.................bbe77777777eee......
                .......feeeeef................beee77777eeeebbb....
                ......feeeddddf..............bbeeeebbeeeeeebbb....
                .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
                ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
                ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
                .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
                .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
                .fef..ffeedddddff...........777bbbbbbbbbb7777b....
                .fef.feeeefffff..f...........774444444444477......
                .feffeeeeeeef...fdf............bbbbbbbbbbbb.......
                ..ffeeeefeeeefffeddf...........bb44bbbbb44b.......
                ...feeeefeeeeefeeef..............44.....44........
                ....feffbdffeeeeef................4.....4.........
                ....fdbbddf.fffff................ee.....ee........
                .....fffff.....................eeee.....eeee......
            """)],
        500,
        False)
    pause(5000)
    game.game_over(True)
sprites.on_overlap(SpriteKind.player, SpriteKind.meta, on_on_overlap4)

animmonkey = False
jump = 0
animcoin: animation.Animation = None
money: Sprite = None
goal_falsa: Sprite = None
goal2: Sprite = None
meta2: Sprite = None
mySprite: Sprite = None
change_level = 0
change_level = 0
mySprite = sprites.create(assets.image("""
    mono
"""), SpriteKind.player)
scene.camera_follow_sprite(mySprite)
mySprite.ay = 300
controller.move_sprite(mySprite, 100, 0)
scene.set_tile_map(assets.image("""
    p
"""))
startstage()
startanimcoin()
startarget()
sprites.destroy_all_sprites_of_kind(SpriteKind.falsa)
sprites.destroy_all_sprites_of_kind(SpriteKind.meta)
game.set_game_over_message(True, "te ganaste el corazon de shrek")

def on_on_update():
    global animmonkey
    animmonkey = controller.right.is_pressed() or controller.left.is_pressed()
    if not (animmonkey):
        animation.stop_animation(animation.AnimationTypes.ALL, mySprite)
game.on_update(on_on_update)
