enum ActionKind {
    Walking,
    Idle,
    Jumping
}
namespace SpriteKind {
    export const goal = SpriteKind.create()
    export const coin = SpriteKind.create()
    export const falsa = SpriteKind.create()
    export const P = SpriteKind.create()
    export const meta = SpriteKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.falsa, function (sprite, otherSprite) {
    game.setGameOverMessage(false, "es shrek es raro...")
    game.gameOver(false)
})
function startarget () {
    scene.placeOnRandomTile(mySprite, 1)
    meta2 = sprites.create(assets.image`shrek0`, SpriteKind.meta)
    goal2 = sprites.create(assets.image`shrek`, SpriteKind.goal)
    goal_falsa = sprites.create(assets.image`shrek falso`, SpriteKind.falsa)
    scene.placeOnRandomTile(goal2, 2)
    scene.placeOnRandomTile(meta2, 14)
    scene.placeOnRandomTile(goal_falsa, 3)
    for (let value of scene.getTilesByType(5)) {
        money = sprites.create(assets.image`Moneda`, SpriteKind.coin)
        scene.place(value, money)
        animation.attachAnimation(money, animcoin)
        animation.setAction(money, ActionKind.Walking)
    }
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.coin, function (sprite2, otherSprite2) {
    sprites.destroy(otherSprite2)
    info.changeScoreBy(1)
    music.play(music.melodyPlayable(music.baDing), music.PlaybackMode.UntilDone)
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    assets.animation`mono derecha`,
    200,
    true
    )
})
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    animation.runImageAnimation(
    mySprite,
    assets.animation`mono izquierda`,
    200,
    true
    )
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (mySprite.isHittingTile(CollisionDirection.Bottom)) {
        mySprite.vy = -150
    } else if (jump == 0) {
        mySprite.vy = -150
        jump = 1
    }
})
scene.onOverlapTile(SpriteKind.Player, assets.image`agua`, function (sprite3, location) {
    game.setGameOverMessage(false, "¡los monos no nadan!")
    game.gameOver(false)
})
scene.onOverlapTile(SpriteKind.Player, assets.image`bola`, function (sprite5, location2) {
    game.setGameOverMessage(false, "¡ay!")
    game.gameOver(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.goal, function (sprite, otherSprite) {
    if (change_level == 0) {
        sprites.destroyAllSpritesOfKind(SpriteKind.goal)
        sprites.destroyAllSpritesOfKind(SpriteKind.coin)
        sprites.destroyAllSpritesOfKind(SpriteKind.falsa)
        sprites.destroyAllSpritesOfKind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.setTileMap(assets.image`segundo nivel`)
        startanimcoin()
        startstage()
        startarget()
    } else if (change_level == 1) {
        sprites.destroyAllSpritesOfKind(SpriteKind.falsa)
        sprites.destroyAllSpritesOfKind(SpriteKind.goal)
        sprites.destroyAllSpritesOfKind(SpriteKind.coin)
        sprites.destroyAllSpritesOfKind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.setTileMap(assets.image`tercer nivel`)
        startanimcoin()
        startstage()
        startarget()
    } else if (change_level == 2) {
        sprites.destroyAllSpritesOfKind(SpriteKind.goal)
        sprites.destroyAllSpritesOfKind(SpriteKind.coin)
        sprites.destroyAllSpritesOfKind(SpriteKind.falsa)
        sprites.destroyAllSpritesOfKind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.setTileMap(assets.image`cuarto nivel`)
        startanimcoin()
        startstage()
        startarget()
    } else if (change_level == 3) {
        sprites.destroyAllSpritesOfKind(SpriteKind.falsa)
        sprites.destroyAllSpritesOfKind(SpriteKind.goal)
        sprites.destroyAllSpritesOfKind(SpriteKind.coin)
        sprites.destroyAllSpritesOfKind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.setTileMap(assets.image`quinto nivel`)
        startanimcoin()
        startstage()
        startarget()
    } else if (change_level == 4) {
        sprites.destroyAllSpritesOfKind(SpriteKind.coin)
        sprites.destroyAllSpritesOfKind(SpriteKind.falsa)
        sprites.destroyAllSpritesOfKind(SpriteKind.goal)
        sprites.destroyAllSpritesOfKind(SpriteKind.meta)
        game.splash("nivel completado")
        scene.setTileMap(img`
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            .......77777ff7777777777777777777...........................
            .......75............777777777777...........................
            .......7777777777..7.777777777777...........................
            ............7......7.75.........7...........................
            ............7...7777.7777777....7...........................
            ............7......747.....77...4...........................
            ............7.7.............77..7...........................
            .1............7.................7...........2...............
            .77777777777777777777777777777777777777777777777............
            999999999999999999999999999999999999999999999999999999999999
            `)
        change_level += 1
        startanimcoin()
        startstage()
        startarget()
    } else if (change_level == 5) {
        sprites.destroyAllSpritesOfKind(SpriteKind.falsa)
        sprites.destroyAllSpritesOfKind(SpriteKind.coin)
        sprites.destroyAllSpritesOfKind(SpriteKind.goal)
        sprites.destroyAllSpritesOfKind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.setTileMap(img`
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            .............77..7..8888888.................................
            ..........57....8...........................................
            .........57....8............................................
            .....1...7....8.............................................
            ....77777...58..............5...............................
            ............8................2..............................
            ............................................................
            999999999999999999999999999999999999999999999999999999999999
            `)
        startanimcoin()
        startstage()
        startarget()
    } else if (change_level == 6) {
        sprites.destroyAllSpritesOfKind(SpriteKind.coin)
        sprites.destroyAllSpritesOfKind(SpriteKind.goal)
        sprites.destroyAllSpritesOfKind(SpriteKind.falsa)
        sprites.destroyAllSpritesOfKind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.setTileMap(img`
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ...............7....77....7.................................
            ..............77..77..77..77................................
            ................77......77..................................
            ...............7..........7.................................
            ...............7...........7................................
            ...............75.......1...7...............................
            ...............7............7...............................
            ...............7............7...............................
            ................7...........7...............................
            .................77........7................................
            ..................77....7777................................
            ...................4...77...................................
            ...................4...4....................................
            ...................4...4....................................
            ...................4...4....................................
            ...................4...4....................................
            ...................4...4....................................
            ...................4...4....................................
            ...................4...4....................................
            ...................4...4....................................
            ...................4...4....................................
            ...................4...4....................................
            ............................................................
            ............5..............5................................
            ............5..............5................................
            ...........555............555...............................
            ..........7.5..............5..7.............................
            ..........7....7777777777.....7.............................
            ..........7....7........7.....7.............................
            ..........7....7........7.....7.............................
            ..........7....7........7.....7.............................
            ..........7....7........7.....7.............................
            ..........7....7........7.....7.............................
            ..........7....7........7.....7.............................
            ..........7....7........7.....7.............................
            ..........7....7........7.....7.............................
            ..........73...7........7.....7.............................
            ..........777777........72....7.............................
            ........................7777777.............................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            999999999999999999999999999999999999999999999999999999999999
            `)
        startanimcoin()
        startstage()
        startarget()
    } else if (change_level == 7) {
        sprites.destroyAllSpritesOfKind(SpriteKind.coin)
        sprites.destroyAllSpritesOfKind(SpriteKind.goal)
        sprites.destroyAllSpritesOfKind(SpriteKind.falsa)
        sprites.destroyAllSpritesOfKind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.setTileMap(img`
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            .1..........................................................
            ............................................................
            7777fff888777....8887ff7....................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            .....2......................................................
            .....888....................................................
            .....888....................................................
            ............................................................
            ............................................................
            ............................................................
            .99999999999999999999999999999999999999999999999999999999999
            `)
        startanimcoin()
        startarget()
        startstage()
    } else if (change_level == 8) {
        sprites.destroyAllSpritesOfKind(SpriteKind.coin)
        sprites.destroyAllSpritesOfKind(SpriteKind.goal)
        sprites.destroyAllSpritesOfKind(SpriteKind.falsa)
        sprites.destroyAllSpritesOfKind(SpriteKind.meta)
        game.splash("nivel completado")
        change_level += 1
        scene.setTileMap(img`
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ...........1............e...................................
            ...........777777777777777..................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            ............................................................
            999999999999999999999999999999999999999999999999999999999999
            `)
        startanimcoin()
        startarget()
        startstage()
    }
})
function startanimcoin () {
    animcoin = animation.createAnimation(ActionKind.Walking, 200)
    animcoin.addAnimationFrame(assets.image`moneda 1`)
    animcoin.addAnimationFrame(assets.image`moneda 2`)
    animcoin.addAnimationFrame(assets.image`moneda 3`)
    animcoin.addAnimationFrame(assets.image`moneda 4`)
    animcoin.addAnimationFrame(assets.image`moneda 6`)
    animcoin.addAnimationFrame(assets.image`moneda 7`)
}
function startstage () {
    scene.setBackgroundColor(9)
    scene.setTile(7, assets.image`pasto`, true)
    scene.setTile(1, assets.image`inicio`, false)
    scene.setTile(2, assets.image`comida`, false)
    scene.setTile(5, assets.image`inicio`, false)
    scene.setTile(9, assets.image`agua`, false)
    scene.setTile(4, assets.image`bola`, false)
    scene.setTile(15, assets.image`pasto falso`, false)
    scene.setTile(3, assets.image`comida`, false)
    scene.setTile(8, assets.image`final`, true)
    scene.setTile(14, assets.image`comida`, false)
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.meta, function (sprite, otherSprite) {
    sprites.destroyAllSpritesOfKind(SpriteKind.Player)
    animation.runImageAnimation(
    meta2,
    [img`
        .................................7..777..7........
        ................................77.77777.77.......
        ..................................7777777.........
        ..................................ee7ee77.........
        .................................7f77f777.........
        .................................777774777........
        .................................744447777........
        .................................777777777........
        ........fffff.................bbe77777777eee......
        .......feeeeef................beee77777eeeebbb....
        ......feeeddddf..............bbeeeebbeeeeeebbb....
        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
        .fef..ffeedddddf............777bbbbbbbbbb7777b....
        .fef.feeeefffff..............774444444444477......
        .feffeeeeeeef..................bbbbbbbbbbbb.......
        ..ffeeeefeffef.................bb44bbbbb44b.......
        ...feeeefeffef...................44.....44........
        ....feffbdfbdf....................4.....4.........
        ....fdbbddcddf...................ee.....ee........
        .....ffffffff..................eeee.....eeee......
        `,img`
        .................................7..777..7........
        ................................77.77777.77.......
        ..................................7777777.........
        ..................................ee7ee77.........
        .................................7f77f777.........
        .................................777774777........
        .................................744447777........
        .................................777777777........
        ........fffff.................bbe77777777eee......
        .......feeeeef................beee77777eeeebbb....
        ......feeeddddf..............bbeeeebbeeeeeebbb....
        .....ffeedfddddc............bbeeeee44eeeeeebbbbb..
        ....fddeedfddffc...........bbbeeeeebbeeeeeeebbbb..
        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
        .fef..ffeedddddf............777bbbbbbbbbb7777b....
        .fef.feeeefffff..............774444444444477......
        .feffeeeeeeef..................bbbbbbbbbbbb.......
        ..ffeeeefeffef.................bb44bbbbb44b.......
        ...feeeefeffef...................44.....44........
        ....feffbdfbdf....................4.....4.........
        ....fdbbddcddf...................ee.....ee........
        .....ffffffff..................eeee.....eeee......
        `,img`
        .................................7..777..7........
        ................................77.77777.77.......
        ..................................7777777.........
        ..................................ee7ee77.........
        .................................7f77f777.........
        .................................777774777........
        .................................744447777........
        .................................777777777........
        ........fffff.................bbe77777777eee......
        .......feeeeef................beee77777eeeebbb....
        ......feeeddddf..............bbeeeebbeeeeeebbb....
        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
        .fef..ffeedddddf............777bbbbbbbbbb7777b....
        .fef.feeeefffff..............774444444444477......
        .feffeeeeeeef..................bbbbbbbbbbbb.......
        ..ffeeeefeffef.................bb44bbbbb44b.......
        ...feeeefeffef...................44.....44........
        ....feffbdfbdf....................4.....4.........
        ....fdbbddcddf...................ee.....ee........
        .....ffffffff..................eeee.....eeee......
        `,img`
        .................................7..777..7........
        ................................77.77777.77.......
        ..................................7777777.........
        ..................................ee7ee77.........
        .................................7f77f777.........
        .................................777774777........
        .................................744447777........
        .................................777777777........
        ........fffff.................bbe77777777eee......
        .......feeeeef................beee77777eeeebbb....
        ......feeeddddf..............bbeeeebbeeeeeebbb....
        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
        .fef..ffeedddddff...........777bbbbbbbbbb7777b....
        .fef.feeeeffffffdf...........774444444444477......
        .feffeeeeeeef.feddf............bbbbbbbbbbbb.......
        ..ffeeeefeeeefeeef.............bb44bbbbb44b.......
        ...feeeefeeeeeeef................44.....44........
        ....feffbdffeeef..................4.....4.........
        ....fdbbddf.fff..................ee.....ee........
        .....fffff.....................eeee.....eeee......
        `,img`
        .................................7..777..7........
        ................................77.77777.77.......
        ..................................7777777.........
        ..................................ee7ee77.........
        .................................7f77f777.........
        .................................777774777........
        .................................744447777........
        .................................777777777........
        ........fffff.................bbe77777777eee......
        .......feeeeef................beee77777eeeebbb....
        ......feeeddddf..............bbeeeebbeeeeeebbb....
        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
        ....fddeedfddfdc..2.2......bbbeeeeebbeeeeeeebbbb..
        ....cdbeeddddeedc.222......bbbbbbbbbbbbbbb77bbbb..
        .ff.cdbeeddcddddc..2........77bbbbbbbbbbbb77bbb...
        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
        .fef..ffeedddddff...........777bbbbbbbbbb7777b....
        .fef.feeeefffff..f...........774444444444477......
        .feffeeeeeeef...fdf............bbbbbbbbbbbb.......
        ..ffeeeefeeeefffeddf...........bb44bbbbb44b.......
        ...feeeefeeeeefeeef..............44.....44........
        ....feffbdffeeeeef................4.....4.........
        ....fdbbddf.fffff................ee.....ee........
        .....fffff.....................eeee.....eeee......
        `,img`
        .................................7..777..7........
        ................................77.77777.77.......
        ..................................7777777.........
        ..................................ee7ee77.........
        .................................7f77f777.........
        .................................777774777........
        .................................744447777........
        .................................777777777........
        ........fffff.................bbe77777777eee......
        .......feeeeef.......2.2......beee77777eeeebbb....
        ......feeeddddf......222.....bbeeeebbeeeeeebbb....
        .....ffeedfddfdc......2.....bbeeeee44eeeeeebbbbb..
        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
        .fef..ffeedddddff...........777bbbbbbbbbb7777b....
        .fef.feeeefffff..f...........774444444444477......
        .feffeeeeeeef...fdf............bbbbbbbbbbbb.......
        ..ffeeeefeeeefffeddf...........bb44bbbbb44b.......
        ...feeeefeeeeefeeef..............44.....44........
        ....feffbdffeeeeef................4.....4.........
        ....fdbbddf.fffff................ee.....ee........
        .....fffff.....................eeee.....eeee......
        `,img`
        .................................7..777..7........
        ................................77.77777.77.......
        ..................................7777777.........
        ..................................ee7ee77.........
        .................................7f77f777.........
        ............................2.2..777774777........
        ............................222..744447777........
        .............................2...777777777........
        ........fffff.................bbe77777777eee......
        .......feeeeef................beee77777eeeebbb....
        ......feeeddddf..............bbeeeebbeeeeeebbb....
        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
        .fef..ffeedddddff...........777bbbbbbbbbb7777b....
        .fef.feeeefffff..f...........774444444444477......
        .feffeeeeeeef...fdf............bbbbbbbbbbbb.......
        ..ffeeeefeeeefffeddf...........bb44bbbbb44b.......
        ...feeeefeeeeefeeef..............44.....44........
        ....feffbdffeeeeef................4.....4.........
        ....fdbbddf.fffff................ee.....ee........
        .....fffff.....................eeee.....eeee......
        `,img`
        .................................7..777..7........
        ................................77.77777.77.......
        ..................................7777777.........
        ..................................ee7ee77.........
        .................................7f77f777.........
        .................................777774337........
        .................................744447777........
        .................................777777777........
        ........fffff.................bbe77777777eee......
        .......feeeeef................beee77777eeeebbb....
        ......feeeddddf..............bbeeeebbeeeeeebbb....
        .....ffeedfddfdc............bbeeeee44eeeeeebbbbb..
        ....fddeedfddfdc...........bbbeeeeebbeeeeeeebbbb..
        ....cdbeeddddeedc..........bbbbbbbbbbbbbbb77bbbb..
        .ff.cdbeeddcddddc...........77bbbbbbbbbbbb77bbb...
        .fef.cfeedddccccc...........77bbbbbbbbbbb7777b....
        .fef..ffeedddddff...........777bbbbbbbbbb7777b....
        .fef.feeeefffff..f...........774444444444477......
        .feffeeeeeeef...fdf............bbbbbbbbbbbb.......
        ..ffeeeefeeeefffeddf...........bb44bbbbb44b.......
        ...feeeefeeeeefeeef..............44.....44........
        ....feffbdffeeeeef................4.....4.........
        ....fdbbddf.fffff................ee.....ee........
        .....fffff.....................eeee.....eeee......
        `],
    500,
    false
    )
    pause(5000)
    game.gameOver(true)
})
let animmonkey = false
let jump = 0
let animcoin: animation.Animation = null
let money: Sprite = null
let goal_falsa: Sprite = null
let goal2: Sprite = null
let meta2: Sprite = null
let mySprite: Sprite = null
let change_level = 0
change_level = 0
mySprite = sprites.create(assets.image`mono`, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
mySprite.ay = 300
controller.moveSprite(mySprite, 100, 0)
scene.setTileMap(assets.image`p`)
startstage()
startanimcoin()
startarget()
sprites.destroyAllSpritesOfKind(SpriteKind.falsa)
sprites.destroyAllSpritesOfKind(SpriteKind.meta)
game.setGameOverMessage(true, "haz ganado el corazón de Shrek")
game.onUpdate(function () {
    animmonkey = controller.right.isPressed() || controller.left.isPressed()
    if (!(animmonkey)) {
        animation.stopAnimation(animation.AnimationTypes.All, mySprite)
    }
})
